### ISSUE TITLE
`generatedCounter` should be the last cell of `generatedTop`

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#3348] opened 2023-04-19 15:27 UTC
Consider the following definition:

```
module TEST-SYNTAX
    imports INT-SYNTAX
endmodule

module TEST
    imports TEST-SYNTAX
    configuration
        <k> $PGM:Int </k>
        <a> $A:Int </a>
        <b> $B:Int </b>
        <c> $C:Int </c>
endmodule
```

when kompiled, the following production is generated:

```k
syntax GeneratedTopCell ::= "<generatedTop>" KCell ACell BCell GeneratedCounterCell CCell "</generatedTop>" [...]
```

That is, `GeneratedCounterCell` gets wedged between `BCell` and `CCell`, which seems random. Instead, one would expect `GeneratedCounterCell` to be the last production item:

```k
syntax GeneratedTopCell ::= "<generatedTop>" KCell ACell BCell CCell GeneratedCounterCell "</generatedTop>" [...]
```

This makes programmatic processing of the configuration more straightforward.

**Comment by dwightguth** [comment] 2023-04-19 16:13
It's probably an off-by-one error.

**Comment by radumereuta** [comment] 2023-04-20 14:26
Probably here: https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/compile/ResolveFreshConstants.java#L178

**Comment by ehildenb** [comment] 2023-04-20 15:57
This needs to be tested with both cases:

- The declared configuration already has a topmost cell, like `configuration <T> <k> ... </k> <state> ... </state> </T>`
- The declared configuration does not have a unique topmost cell, like `configuration <k> ... </k> <state> ... </state>`

**Comment by radumereuta** [comment] 2023-04-20 18:37
This has me beat.
I tried to modify the code [here](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/compile/ResolveFreshConstants.java#L178) and I can successfully modify the production to insert the sort in the correct location.
Then there is a problem in the pretty printer because it outputs something like:
```
<generatedTop>
  <k>
    10 ~> .
  </k>
  <state>
    x |-> 5
  </state>
<generatedCounter>
  0
</generatedCounter>
```
Notice that in the closing cell of `<generatedTop>` is not correct.
For that, I tried to modify the format attribute of this production. So instead of `format(%1%i%n%2%n%4%d%n%5)` I generated  `format(%1%i%n%2%n%4%d%n%6)`. The problem is, somewhere in the rest of the kompile pipeline this gets overridden to the original format.
Now my question is, how did it work before this? Why wasn't the `<generatedCounter>` cell printed?

I'm time-boxing this for now. I'm waiting on some hints from @dwightguth

**Comment by dwightguth** [comment] 2023-04-20 19:30
I believe that the generatedTop cell's format attribute is overridden when the generatedCounter cell is added, ie, the ResolveFreshConstants pass.

**Comment by ehildenb** [comment] 2023-04-27 15:55
We could instead:

- Move the insertion of the format attribute on configuration items the user _did not_ supply the attribute directly for to _after_ the configuration modification passes (including the one that handles inserting `<generatedCounter>`).
- Have the `ResolveFreshConstants.java` not care about the `format` attribute anymore.

**Closed as completed** 2023-05-03 12:42 UTC
