### ISSUE TITLE
Associativity filter exception?

### ISSUE THREAD

**Issue by LaifsV1** [runtimeverification/k#762] opened 2019-09-11 18:26 UTC
What does the associativity filter exception error mean? I get the following error:

    [Error] Critical: Associativity filter exception. Cannot use ___HOLI-SYNTAX as
    a left child of ___HOLI-SYNTAX

I attempted to have a left associative rule for function application:

    > Term Term  [seqstrict(1,2), left]

with the intention of having a rule handle the transition when both terms have been evaluated.

**Comment by dwightguth** [comment] 2019-09-11 18:30
This looks like a parse error because that same klabel is declared somewhere else in the same modeule as right associative or nonassociative.

You have a couple options:

1. You could probably fix this by updating to the llvm backend.
2. You could give one or both productions a unique klabel.

**Comment by LaifsV1** [comment] 2019-09-11 18:37
> that same klabel is declared somewhere else in the same modeule
> You could give one or both productions a unique klabel

What do you mean by the "klabel"? e.g. is it `Term` in `syntax Term ::= Term Term`?

Can a klabel have a different associativity defined indirectly?
e.g. `Block ::= Block Block [right] | Term` and then defining `Term ::= Term Term [left]`?

> You could probably fix this by updating to the llvm backend.

Is this on the latest release? Can I do "--backend llvm"?

**Comment by dwightguth** [comment] 2019-09-11 19:47
Yes, the llvm backend is ready for use on the latest release. If you run into issues, let me know. There are still some unimplemented features but it should support most things and in general I'm more likely to spend time fixing issues there than on the ocaml backend.

By the `klabel` I am referring to `___HOLI-SYNTAX` which is generated by replacing all the nonterminals in the production with underscores and appending the name of the module. You have two different productions with the same klabel here, and thus the ocaml backend does not know how to tell them apart. It is an unfortunate default that was fixed in the llvm backend, but we were unable to fix it retroactively. Thus if you want to continue to use the ocaml backend (which is likely to be deprecated relatively soon, by the way), you will have to set the klabel attribute on one or both of those two productions.

**Comment by LaifsV1** [comment] 2019-09-11 20:14
Thanks! I'm running an old version of K (Mon Apr 29 06:19:50 BST 2019), and the llvm backend doesn't work. I'll get the lastest release and test it. Will the Java backend work fine?

**Comment by ehildenb** [comment] 2020-12-08 17:32
Closing as this is targeting an old backend. If it's still an issue on the LLVM or Haskell backends, please open a new bug report with reproduction steps.

**Closed as completed by ehildenb** 2020-12-08 17:32 UTC
