### ISSUE TITLE
kprove unsound when a spec rule leads to infinite loop

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/k#82] opened 2018-05-27 15:18 UTC
Look at this (incorrect) rule:
```
    rule A => false
        requires  chop( 1 &Int bool2Word ( A ) ) ==K 0 [trusted]
```

It will be compiled into a spec rule, not a function rule, e.g.: `<k> A => false ...</k>...`
Now if this rule applies once, it will normally continue to apply indefinitely, rewriting the spec to itself. kprove has a mechanism to prevent this: 

https://github.com/kframework/k5/blob/7aa7d407a89ccb682729153f3808a239e0a7face/java-backend/src/main/java/org/kframework/backend/java/symbolic/SymbolicRewriter.java#L624-L625

If a a configuration is encountered the 2nd time, the respective path will be considered proven. Thus, in our case kprove will report that spec is proved, while in fact it would execute indefinitely. I propose considering looping path "not proven" and print an appropriate message. Will submit a fix ASAP.

**Comment by ehildenb** [comment] 2018-05-27 15:40
@denis-bogdanas I'm not sure this is correct. Everything is true about infinite repeating paths in Reachability Logic (the "relative" part of relatively complete).

Perhaps the issue is more about how the looping behavior is in the side condition, so isn't actually making progress? @bmmoore?

I'm confused by your example though, the above rule, compiled into `<k> A => false ... </k>, should *not* apply to the `A` in the side-condition, which does not show up at the front of the `<k>` cell. Can you provide the full definition?

**Comment by denis-bogdanas** [comment] 2018-05-27 15:53
It has nothing to do with side condition. I put here the rule that gave me headaches unchanged. If A is `false`, the rule will rewrite the the configuration to itself. If it wouldn't be for the cited piece of code, this would lead to infinite loop.

I agree that this is not an issue in the sense of partial correctness, but we can reasonably assume a computation that does not finish is an undesirable behavior and has to be reported. In this precise case it was caused by an error in my helper rule.

**Comment by ehildenb** [comment] 2018-05-27 16:14
I still don't understand. Computation that does not finish has every reachability claim about it true, so it should prove it. The only case I could see an argument otherwise if side-conditions are expected to be evaluated fully (and must have closed finite proof trees), which I think @bmmoore can probably answer.

Unless by "computation that does not finish" you mean the kprover itself gets stuck in an infinite loop (and are not referring to the execution traces of the program).

**Comment by denis-bogdanas** [comment] 2018-05-27 16:40
I agree that reachability claims are satisfied. What I say is that computation that does not finish represents a possible issue that should be reported to the user, regardless of whether reachability is satisfied. Right now it is simply swallowed and specification is proved correct with no explanation.

In this particular case that I encountered, I was tempted to just consider my specification finished and go on with the next task. Yet there was something dubious about the way it was proved, so I spent one more day investigating. This report is the result of the effort. And it turns out the spec was not proved at all. I just wrote some ridiculously wrong helper rules that made all execution paths to not terminate. The spec was proven vacuously.

I would prefer to see a warning like "infinite loop detected". Maybe adding the non-finishing condiguration to the list of final configurations is not correct, but at least we have to report a warning.

**Comment by ehildenb** [comment] 2018-05-27 16:46
Well, any time there is a loop-invariant in the spec, it will be printed to this list of looping rules, right? And the user will expect it to be looping, so it will be information they already know. I'm not sure it makes sense to print it every time. Maybe we could add an explicit `loop` attribute to rules which then if it's looping and the user did not add it, then they get the warning? But I think it will be quite too much output if every loop invariant is re-printed after the proof.

**Comment by denis-bogdanas** [comment] 2018-05-27 18:28
Oh, there are also loop invariants... Never had to deal with them yet. I agree with loop attribute proposal.

**Closed as completed** 2018-07-26 17:55 UTC
