### ISSUE TITLE
Consider to use tree-sitter instead of flex/bison

### ISSUE THREAD

**Issue by XVilka** [runtimeverification/k#1032] opened 2020-01-16 10:55 UTC
[Tree-sitter](http://tree-sitter.github.io/tree-sitter/) is a parser generator tool and an incremental parsing library. It can build a concrete syntax tree for a source file and efficiently update the syntax tree as the source file is edited. Tree-sitter aims to be:
- General enough to parse any programming language
-  Fast enough to parse on every keystroke in a text editor
-  Robust enough to provide useful results even in the presence of syntax errors
- Dependency-free so that the runtime library (which is written in pure C) can be embedded in any application

It also has an impressive list of already available parsers here: http://tree-sitter.github.io/tree-sitter/#available-parsers

**Comment by radumereuta** [comment] 2020-01-16 11:43
I just glanced at what tree-sitter can do, and what was designed to do, so please correct me if I'm wrong.
Parsing a K definition is actually fairly complicated to parse. It's a two-step process:
- parse the syntax declarations (we call it outer parsing) and ignore the rules (we put them in 'bubbles')
  - combine the user-defined language with the K syntax, and generate a new parser
- parse configuration and rules.

Since we have a dynamically generated parser, we don't have much control over the resulting grammar, so most of the time, we have ambiguities. We rely on those ambiguities to do type inferencing. Then we trim down the erroneous branches until we are left with one of: parsing error, ambiguity error, clean tree.

I haven't seen any mention of tree-sitter being able to return ambiguous trees.
I've looked over the C grammar and tested a quick example:
```
#include <stdio.h>
typedef int a;
void main(int l, int argv[]) {
  int b, c;
  a *d;
  b *c;
}
```
Both `a*d` and `b*c` are parsed as pointer declaration, which is wrong. The second one is multiplication. This leads me to believe they solve this problem statically by just choosing one when they design the grammar.

I don't think Bison cand handle ambiguities either, but we only use it as an option when it's possible. Just to speed up things a bit.

Someone else from the K team, please correct me if I'm wrong.

**Comment by dwightguth** [comment] 2020-01-16 17:45
I am unable to find reference in their documentation to what types of grammars they accept, which is somewhat suspect in itself, but from their documentation about precedence and associativity it is clear that they do not support GLL or GLR grammars, so it's true that this is not going to be suitable for parsing K definitions.

Moreover, it appears that grammars are written in JavaScript, so it's unlikely that we would choose such a library as a dependency of the project when this would introduce yet another programming language to the mix in a project that already is quite complex to build as a result of the mix of programming languages it depends on.

**Comment by ehildenb** [comment] 2020-01-16 17:49
If it can't handle ambiguities it's basically a non-starter for us. But being able to use that parser for editor integration is attractive, since we can then generate a parser for the language, and immediately have editor integration for that language.

Currently we generate a Bison parser which _is not guaranteed to work_ if you grammar doesn't have nice LR(1) properties. That is to be only used in cases where you know your grammar is OK, and want a fast parser for skipping the frontend execution with.

We've been having some discussions about adding another option for Happy (instead of Bison) alongside, which does support ambiguities in the parse. @mattoxb knows more about that.

**Comment by ehildenb** [comment] 2020-12-15 17:52
Closing this as it's not actionable.

**Closed as completed by ehildenb** 2020-12-15 17:52 UTC
