### ISSUE TITLE
Wrong sort inference while parsing.

### ISSUE THREAD

**Issue by tomtomjhj** [runtimeverification/k#36] opened 2018-03-08 00:57 UTC
I kompiled [simple-typed-static.k](https://github.com/kframework/k5/blob/master/k-distribution/tutorial/2_languages/1_simple/2_typed/1_static/simple-typed-static.k) and kran the [programs](https://github.com/kframework/k5/tree/master/k-distribution/tutorial/2_languages/1_simple/2_typed/programs) manually, the resulting type of a function contains `.Params` in its argument `Types` instead of `.Types`.

For example, `krun exceptions_01.simple` gives following results:
```
<T>
  <tasks>
    .TaskCellBag
  </tasks>
  <gtenv>
    main |-> void , .Params -> void
  </gtenv>
</T>
```
Something similar happened when I tried to put `Types` sort entry into a cell with default item `.Types`.
```
  syntax Decl ::= Type Exps ";"
                | Type Id "(" Params ")" Block
                | Type Id "(" Params ")" "throws" Types Block

...

  configuration <T color="yellow">
                  <tasks color="orange">
                    <task multiplicity="*" color="yellow">
                      <k color="green"> $PGM:Stmts </k>
                      <tenv multiplicity="?" color="cyan"> .Map </tenv>
                      <returnType multiplicity="?" color="black"> void </returnType>
                      <mayThrow multiplicity="?" color="grey"> .Types </mayThrow>
                    </task>
                  </tasks>
                  <gtenv color="blue"> .Map </gtenv>
                </T>
...
  rule
    <task> <k> T:Type F:Id(Ps:Params) throws Ts:Types S:Block => getTypes(Ps)->T F; ...</k> </task>
    (.Bag => <task>
               <k> mkDecls(Ps) S </k>
               <tenv> .Map </tenv>
               <returnType> T </returnType>
               <mayThrow> Ts </mayThrow>             /////////////////// Line 146
             </task>)
    [structural]
```
Kompiling `simple-typed-static.k` with some rules and syntax added as above gives following result:
```
[Error] Compiler: Had 1 parsing errors.
[Error] Critical: Unexpected sort Types for term Ts. Expected Params.
	Source(/some/random/directory/simple-typed-static.k)
	Location(146,29,146,31)  
```
Error disappeared when I put `.` or `.Params` in Line 146.

If I put `.Types` in the Line 146, kompile fails with the following message:
```
[Error] Compiler: Had 1 parsing errors.
[Error] Inner Parser: Parse error: unexpected token '</throwsType>'.
	Source(/some/random/directory/simple-typed-static.k)
	Location(146,36,146,49)
```
I should I deal with it?

**Comment by ehildenb** [comment] 2022-10-06 19:47
`<mayThrow>` is not a cell that exists in the SIMPLE semantics (and never did AFAICT). So we need a full example to reproduce properly. In light of that, I will close this unless you can provide a self-contained full example. I was not able to reproduce.

This issue is so old at this point anyway, that I think it may not be relevant anymore anyway.

**Closed as completed by ehildenb** 2022-10-06 19:47 UTC
Labels: parsing, needs-reproducing
