### ISSUE TITLE
FUN definition adds subsort into KVar

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1587] opened 2020-10-08 16:37 UTC
Due to #1568. We are adding a subsort to `KVar`, which means we're adding constructors to a builtin sort.

Possible solutions:

-   Relax this error on Java backend for sort `KVar` because FUN only runs on Java backend.
-   Rework substitution based FUN to not have `KVar` be subsorted.

**Comment by dwightguth** [comment] 2022-10-18 21:31
This is a duplicate of #1271

**Closed as not planned by dwightguth** 2022-10-18 21:31 UTC
Labels: bug
