### ISSUE TITLE
NullPointerException when adding any new syntax to a module

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/k#876] opened 2019-11-06 13:03 UTC
- Where: [wasm-semantics repo](https://github.com/kframework/wasm-semantics), in the file `kwasm-lemmas.md`, the module `WRC20`.
- What: NullPointerException from `kprove` when any new `syntax` is added to the `WRC20` module.

The issue seems to only occur when modifying the `WRC20` module, not the `KWASM-LEMMAS` module (which imports `WRC20`).

# Steps to reproduce

Clone [wasm-semantics repo](https://github.com/kframework/wasm-semantics)

`cd` in and do

```sh
git checkout syntax-npe-bug &&
make deps &&
make build -j4
```

Uncomment any of the commented out `syntax` declarations at the top of the WRC20 module.
```
    //syntax Instr ::= "new" // Causes NPE.
    //syntax Int ::= Int "myOp" Int [function] // Causes NPE.
    //syntax IType ::= "i32" // Causes NPE.
```

then invoke the prover in either of the following ways:
```
make build -j4 && make tests/proofs/wrc20-spec.k.prove PROVE_OPTIONS=--debug
make build -j4 && make tests/proofs/wrc20-spec.k.klab-prove PROVE_OPTIONS=--debug
```

It should suffice to build the corresponding backend with `make build-haskell` or `make build-java`.

The definitions get built in `.build/defn/{{backend name}}

**Comment by denis-bogdanas** [comment] 2019-11-06 13:47
In the current implementation new syntax can only be added to the module specified by `-m` option of to `kprove`. The other modules referred by specification file but not by `-m` module should only contain specification rules. But it is worth adding a better error message.

**Comment by hjorthjort** [comment] 2019-11-06 14:04
What confuses me then is the existing syntax rules in the WRC20 module. Why
do they work?

Note that `KWASM-LEMMAS` imports `WRC20`. Shouldn't that be enough? I thought importing was basically equivalent to inlining.

**Comment by dwightguth** [comment] 2019-11-06 19:51
This is now a duplicate of #239.

**Closed as completed by dwightguth** 2019-11-06 19:51 UTC
