### ISSUE TITLE
[Bug] krun unable to unparse symbolic ints to kore `(NoSuchElementException: key not found: #SemanticCastToInt)`

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#1682] opened 2020-12-02 01:30 UTC
K Version
---------

```
RV-K version 1.0-SNAPSHOT
Git revision: ada1ae8
Git branch: UNKNOWN
Build date: Sun Nov 29 17:43:14 CST 2020
```

Description
-----------

See title

Reproducing
-----------

Running this definition with `--output kore` crashes.

```
module TEST
    imports INT
    configuration <k> .K </k>
    rule <k> .K => ?_:Int </k> 
endmodule
```

```
$ kompile test.k --backend haskell
$ krun  
<k>
  'QuesUnds'0:Int ~> .
</k>
$ krun  --output kore
[Error] Internal: Uncaught exception thrown of type NoSuchElementException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
(NoSuchElementException: key not found: #SemanticCastToInt)
```

Expected Behavior
-----------------

Correct kore output

**Comment by radumereuta** [comment] 2020-12-04 21:57
I think this is a duplicate of #1509.
When loading from Kore into K internal data structures, when you have an injection on top of a variable it gets converted into a cast:
https://github.com/kframework/k/blob/master/kore/src/main/scala/org/kframework/parser/kore/parser/KoreToK.scala#L120
But when pretty-printing it does not get reversed.

**Comment by ehildenb** [comment] 2020-12-08 18:22
The linked code should insert this production not in the KoreToK pass, rather in the KoreToTreeNodes pass.

Add annotation `Sort` class keyed attribute to KVariable so that the injections pass knows how to insert the correct injections (read this attribute in KoreToTreeNodes and correctly turn it into a cast).

**Closed as completed** 2021-01-13 18:49 UTC
Labels: bug
