### ISSUE TITLE
Z3 translation error on equality between two elements that have subsort relation

### ISSUE THREAD

**Issue by yzhang90** [runtimeverification/k#902] opened 2019-11-13 19:28 UTC
In the evm-semantics, `ByteArray` is the subsort of `AccountCode`. It has the following rule:
```
    rule <k> #newAccount ACCT => #end EVMC_ACCOUNT_ALREADY_EXISTS ... </k>
         <account>
           <acctID> ACCT  </acctID>
           <code>   CODE  </code>
           <nonce>  NONCE </nonce>
           ...
         </account>
      requires CODE =/=K .ByteArray orBool NONCE =/=Int
```

When translating the side condition `CODE =/=K .ByteArray` into Z3, `CODE` is of sort `AccountCode` but `.ByteArray` is of sort `ByteArray`. The sort mismatch will cause Z3 and the java backend to crash.

**Comment by ehildenb** [comment] 2020-12-15 17:47
Because this is a Java backend error, I'm closing this. If this is reproducible on the Haskell backend, please open a new bug report with reproduction steps targeting that backend.

**Closed as completed by ehildenb** 2020-12-15 17:47 UTC
