### ISSUE TITLE
`setenv` specifying opam root causes lots of noisy output

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1314] opened 2020-05-30 23:59 UTC
In the `setenv` script here: https://github.com/kframework/k/blob/f537759890446bd6e9e0a2aea5bd83612e22600d/k-distribution/src/main/scripts/lib/setenv#L25

If we are using a global install of K, this will set the opam root to something like `/usr/lib/kframework/opamroot`, which is not a directory writeable by the user account in most cases.

This causes quite a bit of noise from `opam` when using `krun` (even when not using the OCaml backend at all), for example see the output of the `Cross-Validation` test-suite here: https://office.runtimeverification.com/jenkins/blue/organizations/jenkins/michelson-semantics/detail/PR-39/26/pipeline/76

**Comment by ehildenb** [comment] 2020-05-31 00:00
Note that the linked PR is on the Michelson Semantics, which is using opam 2.0, even though the K docker image is created with opam 1.2 installed. So if that is the problem, maybe a fix is here: https://github.com/kframework/k/pull/1313

**Comment by dwightguth** [comment] 2020-06-01 19:43
Most likely the solution is to make sure that `/usr/bin` is at the front of the path when invoking `setenv`. This would mean that if the user installs the kframework debian package, they will get the debian-installed version, 1.2, when running this command, which is what we want.

**Comment by dwightguth** [comment] 2020-06-01 19:48
I'm actually confused by this error. It looks like we're already doing what I just described... When setenv is invokec, K_LIB_DIR gets set to `/usr/lib/kframework`, and then PATH gets set to `/usr/lib/kframework/../../bin:$PATH` which means that /usr/bin is now at the front of the PATH. So unless the user is installing opam 2.0 into /usr/bin (which they should not be doing; if they need their own version of opam it should go in /usr/local/bin), then they should invoke the 1.2 version of opam that gets installed as part of the K package, which should in turn mean that they don't get any errors reported.

I can't fix the scenario where files in /usr point to completely different, non-backwards-compatible versions of the same projects that K depends on; that's just a messed up linux installation.

**Comment by ehildenb** [comment] 2020-06-01 20:24
Well the Michelson semantics needs opam 2.0 installed, so it does install opam 2.0 into the K docker image.

One potential solution of this is to just install opam 2.0 into the K docker image, a la https://github.com/kframework/k/pull/1313 (which it looks like you closed).

I'm not sure why the user should be forced to prefer our version of opam over theirs actually, that doesn't really make sense to me. But I guess we would have the same problem (in reverse) if we installed opam 2.0 by default in the docker image, and they needed opam 1.2?

Either way, we're the only users of the docker images, and the only one of our projects that cares about the opam version is Tezos, so I don't really see a reason not to just do opam 2.0 by default in the docker image.

**Comment by dwightguth** [comment] 2020-06-02 02:43
I mean, if you need opam 2.0, just install it to /usr/local. It shouldn't conflict with the installation of opam 1.2 being used by the ocaml backend.

**Comment by sskeirik** [comment] 2020-06-02 16:19
We are using the version of opam provided by an upstream maintained PPA from the ocaml devs, so we can't change where we want to install it unless we decide to do a custom install instead of relying on the PPA. Thoughts?

**Comment by dwightguth** [comment] 2020-06-02 18:55
it sounds like there is a problem associated with the debian package of K and opam 2. I will try and get the focal fossa debian package building on CI, since that is something we need to do anyway. If I run into this same problem, I will try and come up with a solution. If I don't, it's probably not worth fixing. If I do fix it for focal fossa, it ought to become fixed for your PPA as well.

**Comment by dwightguth** [comment] 2020-06-02 19:57
I am unable to reproduce this with opam 2.0 as installed from Ubuntu Focal Fossa. I would suggest you migrate your build of michelson to use Focal instead of an opam ppa if you need opam 2.0. I am going to close this because it is almost certainly some kind of local problem involving your project's PPA and as such is not an issue with K per se.

**Closed as completed by dwightguth** 2020-06-02 19:57 UTC

**Comment by ehildenb** [comment] 2020-06-03 13:13
@dwightguth the build of Michelson is relying on the K dockerhub image, so this would require using Focal Fossa for the K dockerhub image. Is that what you want to do?

**Comment by dwightguth** [comment] 2020-06-03 15:28
I'm fine with that as a solution.
