### ISSUE TITLE
`krun --debugger` should drop us into the `kore-repl` when using the haskell backend

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#1397] opened 2020-07-06 14:45 UTC

**Comment by dwightguth** [comment] 2020-07-06 15:32
I agree, but this is not actionable currently because the repl only currently works on proofs.

**Comment by ehildenb** [comment] 2020-07-06 19:20
Duplicate of #1289 ?

**Comment by nishantjr** [comment] 2020-07-07 15:23
Looks like. Didn't see that.

**Closed as completed** 2020-07-08 14:41 UTC
