### ISSUE TITLE
[K-Bug] KEVM conformance test hanging due to optimisations on llvm backend

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/k#3365] opened 2023-04-26 13:04 UTC
### What component is the issue in?

llvm-backend

### Which command

- [ ] kompile
- [ ] kast
- [X] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

K version:    v5.6.42 Build date:   Tue Apr 11 19:35:49 EEST 2023

### Operating System

Linux

### Steps to Reproduce

1. In evm-semantics, check out [this branch](https://github.com/runtimeverification/evm-semantics/pull/1743).
2. Build dependencies using `make kevm-pyk; make deps`
3. Build the semantics for llvm-backend using debugging symbols `make build-llvm KEVM_OPTS=--enable-llvm-debug`
4. Run the test ` make tests/ethereum-tests/BlockchainTests/GeneralStateTests/stTimeConsuming/CALLBlake2f_MaxRounds.json.run` and notice it is passing.
5. Rebuild the semantics without the debugging symbols `make build-llvm -B`
6. Run the same test and notice that is hanging and does not finish.

### Expected Results

I expect the debug symbols to not affect the execution of the test and to either pass or fail.

**Comment by Baltoli** [comment] 2023-04-27 14:35
The `--enable-llvm-debug`  flag doesn't just enable debug symbols, it changes the optimisation level used by clang. The first debugging step here should be to take a look at the LLVM IR that the code generator has produced with and without `--enable-llvm-debug` to see if we're introducing an infinite loop or similar

**Comment by Scott-Guest** [comment] 2023-05-04 14:43
I was able to reproduce the hang, but as far as I can tell the generated IR is the same in both cases:

```
#!/bin/bash
set -e
set -x

rm -f yes-debug.kore no-debug.kore yes-debug.ll no-debug.ll yes-debug-strip.ll no-debug-strip.ll
make clean
make kevm-pyk
make deps

make build-llvm KEVM_OPTS=--enable-llvm-debug
cd .build/usr/lib/kevm/llvm
cp definition.kore ../../../../../yes-debug.kore
llvm-kompile-codegen definition.kore dt/dt.yaml dt 1 > ../../../../../yes-debug.ll
cd ../../../../..

make build-llvm -B
cd .build/usr/lib/kevm/llvm
cp definition.kore ../../../../../no-debug.kore
llvm-kompile-codegen definition.kore dt/dt.yaml dt 0 > ../../../../../no-debug.ll
cd ../../../../..

diff -q yes-debug.kore no-debug.kore

opt -S -strip-debug no-debug.ll > no-debug-strip.ll
opt -S -strip-debug yes-debug.ll > yes-debug-strip.ll

diff no-debug-strip.ll yes-debug-strip.ll
```
@Baltoli Would you mind double checking this on your machine and seeing if you get the same?

**Comment by Baltoli** [comment] 2023-05-04 14:44
Yep, will do

**Comment by Baltoli** [comment] 2023-05-04 14:47
Try passing `1` to `llvm-compile-codegen` and seeing if it still reproduces.

**Comment by Scott-Guest** [comment] 2023-05-11 04:24
Hmm, I thought the test was hanging when I initially reproduced it on my MacBook, but I left it running for awhile on my PC and it actually finishes after about 20 minutes (compared to only 3 minutes when compiled with debug symbols).

@anvacaru Can you try leaving it running for awhile and seeing if it eventually finishes on your machine as well?

If I'm understanding `opt -strip-debug` correctly, it also appears the generated LLVM IR is still the same when compiling with or without debug symbols. @Baltoli I'd appreciate it if you could re-run (and re-sanity-check :smile:) the updated script above and confirm.

I'm a bit at a loss here, the large time difference is very bizarre - particularly given that the debug version is the faster one.

**Comment by anvacaru** [comment] 2023-05-11 07:08
I re-run the test and can now confirm it passes in around 20 minutes (20:20.31elapsed).

**Comment by Baltoli** [comment] 2023-05-11 09:09
@Scott-Guest from what you're describing here, it seems like the problem is more likely to be to do with the optimisations applied by clang et. al. to the code-generated module, rather than the addition of debug symbols to the same module.

The `--enable-llvm-debug` flag adds `-g -O1` to the options passed to clang: https://github.com/runtimeverification/k/blob/4c09d86ed218ee08d521c5780b0368dc5f330383/llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMBackend.java#L136-L139

If you have a test that you can run in 20 minutes, perhaps take a look at running it in a profiler to see where it's spending its time. The best way to do this is if you can narrow down the "hanging" test to a specific invocation of a kompiled interpreter binary; let me know if you want a hand doing so.

**Comment by Scott-Guest** [comment] 2023-05-15 14:37
Almost all of the time is spent in `blake2b_compress` (https://github.com/runtimeverification/blockchain-k-plugin/blob/23fb5e8fdb4a87451fd40a0e49118eaab481931b/plugin-c/blake2.cpp#L36), which is as expected because this test was specifically constructed to make `uint32t_t rounds` as large as possible (4294967295).

It looks like compiling with `-O1` is entirely responsible for the time difference, and adding it to the non-debug mode fixes the issue.

**Comment by Baltoli** [comment] 2023-05-15 14:39
Huh, that's really interesting - if it's that crypto function responsible for the run-time, are you able to extract the IR at each optimisation level to see what's going on?

**Comment by Scott-Guest** [comment] 2023-05-15 15:02
Looking into that now, here are the files if you're interested: 
[blake2_O0.ll](https://github.com/runtimeverification/k/files/11479085/blake2_O0.ll.txt)
[blake2_O1.ll](https://github.com/runtimeverification/k/files/11479086/blake2_O1.ll.txt)

**Comment by Baltoli** [comment] 2023-05-15 15:11
Closing as the solution is for EVM to just compile with O1.

**Comment by Scott-Guest** [comment] 2023-05-15 21:04
Re-opened.

There is a very large speed difference in `blake2.cpp` when using `-O0` versus `-O1` (enough that EVM might still want to compile with `-O1` by default), and that does explains the time difference between running with/without LLVM debug symbols.

However, if we build in release mode as CI does, which implies `-O2`, the hang still occurs. This was mentioned in the original PR, but I completely glanced over it.

The difference is due to `COOL_RESULT_CONDITION` not being included in `ResolveHeatCoolAttribute` when `-O2` is enabled: https://github.com/runtimeverification/k/blob/2ce169edfbb1841e38fe57df5aa073964328582d/kernel/src/main/java/org/kframework/backend/kore/KoreBackend.java#L48

In the KORE, the difference manifests in the cooling rules for `#refund`, `Ccall`, `Ccallgas`, and `Cselfdestruct` not requiring `isKResult` when `-O2` is enabled:

[O1.kore](https://github.com/runtimeverification/k/files/11481952/O1.kore.txt)
[O2.kore](https://github.com/runtimeverification/k/files/11481953/O2.kore.txt)

If we always include `COOL_RESULT_CONDITION`, the hang is resolved.

**Closed as completed** 2023-05-24 20:33 UTC
