### ISSUE TITLE
[Bug] krun - WasmString macros no longer expand correctly

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/k#1947] opened 2021-04-28 15:33 UTC
K Version
---------

Tell us what version of K you are using.

Example:

```
$ krun --version
K version:    5.1.0
Build date:   Tue Apr 27 10:54:50 UTC 2021
```

Description
-----------

I have this function declared:
```   
syntax WasmStringToken ::= #unparseWasmString ( String          ) [function, functional, hook(STRING.string2token)]
```
Basically it should behave as `rule #unparseWasmString(S) => #token(S, "WasmStringToken")`
It's been working up until now in the following rule, (see side conditions)
```    rule <instrs> #import(MOD, _, #funcDesc(... id: OID, type: TIDX))
               => #func(... type: TIDX, locals: [ .ValTypes ], body: spectest_trap .Instrs, metadata: #meta(... id: OID, localIds: .Map))
               ...
         </instrs>
      requires MOD ==K #unparseWasmString("\"spectest\"")
        orBool MOD ==K #unparseWasmString("\"test\"")
```
That rule stopped matching with the latest K update (hence this update failing): https://office.runtimeverification.com/jenkins/blue/organizations/jenkins/wasm-semantics/detail/PR-417/1/pipeline

It works if I switch to using `#token(S, "WasmStringToken")` directly.

I think we didn't have `#token` when I implemented this, or I wasn't aware of it. I'm happy to switch to using `#token` now, it simplifies the grammar a bit too. But I just wanted to check whether it was intentional that the `hook(STRING.string2token)` has changed behavior.

**Comment by hjorthjort** [comment] 2021-04-28 15:38
Reproduction:

In kframework/wasm-semantics:

```
make deps && make build-llvm && make tests/wasm-tests/test/core/start.wast.run-term
```

- Works at commit `7e5a430291fdf0244bcf4efdef207d3c9279ff2d`
- Breaks at commit `857cbe4f4e2cd4418e4adc7cb61d11be1abbd581` (deps/k updated to latest version)
- Fixed at commit `12e9f2d1c2434a513f119e9e496e4fcbc8fb0403` by replacing `#unparseWasmString` with `#token` as described above.

**Comment by radumereuta** [comment] 2021-04-28 15:43
What commits are these? I can't find them in the K repo. Normally, if they are hashes from this project, GitHub will automatically create a link.
Also, when you run `krun -v` on K built from code you don't get the correct version number. @ehildenb this can be a problem for error reporting.

**Comment by hjorthjort** [comment] 2021-04-29 14:50
Hmm, seems the commits got pruned when the branch was deleted from GitHub. I pushed them up again. See branch https://github.com/kframework/wasm-semantics/tree/token2string-issue
It's the last 3 commits.

**Comment by ehildenb** [comment] 2021-05-04 16:57
Initially we thought this was because of the constant-folding pass added to the Kompile pipeline, right? Have we confirmed which commit of K causes the regression? (bisect)

**Comment by radumereuta** [comment] 2022-10-17 19:29
I'm not sure this is related to macros, maybe more related to this issue that was recently fixed:
https://github.com/runtimeverification/k/pull/2968
Since there isn't a minimal example to quickly test, I would suggest closing this and seeing if it resurfaces.

**Comment by dwightguth** [comment] 2022-10-18 21:55
Closing since we can't reproduce it. Feel free to reopen with an example if you have one.

**Closed as not planned by dwightguth** 2022-10-18 21:55 UTC
Labels: bug, needs-reproducing
