### ISSUE TITLE
Modify tutorial to not use type Bag (so kore backends work)

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/k#1419] opened 2020-07-13 11:57 UTC
There's a test for bag cells for Java backend, which doesn't work on LLVM:
To enable on LLVM:
File `regression-new/cell-sort-llvm/Makefile`
```
DEF=../cell-sort/test
EXT=test
TESTDIR=../cell-sort
KOMPILE_BACKEND=llvm

include ../../../include/ktest.mak
```

Result: either test should pass or throw a meaningful error that cell bags are not supported.
Actual: no idea, Jenkins is down at the time of editing, but none of the above.

**Comment by ehildenb** [comment] 2020-07-16 16:39
-    Error at kompile time: 1111
-    Support bags:
-    Make Set the default instead of Bag: 1

**Comment by ehildenb** [comment] 2020-11-10 18:56
Take this test that @denis-bogdanas supplies, copy it to checks directory, and make sure that it generates the correct error message output file (after adding the appropriate Java code).

**Comment by ehildenb** [comment] 2020-11-10 18:57
In a given test directory, you can run a test:

```
make
```

You can also call (to just update the committed expected output files):

```
make update-results
```

Then you can use `git diff` to see the updated output.

**Comment by radumereuta** [comment] 2020-11-10 20:18
@ehildenb this issue has already been fixed by @dwightguth with #1437

**Comment by nblei** [comment] 2020-12-04 02:42
[Error] Compiler: Cell bags are only supported on the Java backend. If you want
this feature, comment on https://github.com/kframework/k/issues/1419 . As a
workaround, you can add the attribute type="Set" and add a unique identifier to
each element in the set.
	Source(/magnetic/courses/k/tutorial1/imp++/./imp.k)
	Location(41,17,51,21)

pops up when working through the tutorial for imp++.  Would be nice to have this feature in the LLVM backend (or modify the tutorial).

**Comment by ehildenb** [comment] 2020-12-04 04:17
Reopening but changing target to modification of the tutorial.

**Comment by Instein98** [comment] 2022-04-02 19:11
```log
k/k-distribution/pl-tutorial/1_k/4_imp++/lesson_6$ kompile imp.k
[Error] Compiler: Cell bags are only supported on the Java backend. If you want
this feature, comment on https://github.com/runtimeverification/k/issues/1419 .
As a workaround, you can add the attribute type="Set" and add a unique
identifier to each element in the set.
	Source(/home/yicheng/courses/422/k/k-distribution/pl-tutorial/1_k/4_imp++/lesson_6/imp.k)
	Location(41,17,51,21)
[Error] Compiler: Had 1 structural errors.
```
`kompile` got this error during compilation. Could anyone please tell me how to fix the imp.k?
I've tried to change the `.Bag` to `.` (just like the code in [tutorial README](https://github.com/runtimeverification/k/blob/master/k-distribution/pl-tutorial/1_k/4_imp%2B%2B/lesson_6/README.md)). However, I had another error:
```
[Error] Inner Parser: Parse error: unexpected token '.' following token '('.
	Source(/home/yicheng/courses/422/k/k-distribution/pl-tutorial/1_k/4_imp++/lesson_6/imp.k)
	Location(101,10,101,11)
[Error] Compiler: Had 1 parsing errors.
```

**Comment by ehildenb** [comment] 2022-10-06 20:06
Related: https://github.com/runtimeverification/k/issues/1271

**Comment by dwightguth** [comment] 2022-10-18 21:27
Closing as duplicate of #1271

**Closed as not planned by dwightguth** 2022-10-18 21:27 UTC
Labels: checks
