### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by dvc94ch** [runtimeverification/k#91] opened 2018-06-04 15:49 UTC
Tried rendering using kdoc, realized that it requires an older version, installed k3.6 and still doesn't work. Is there a prerendered pdf somewhere? K seems to have some rough edges to get up and running with :/

The tutorials also seem out of date, I'm having trouble getting them to run properly in k5.

People that aren't familiar with ocaml would also need to know the following:
* doesn't work with opam 2 beta (as installed by default on fedora) which takes a while to debug (symptom is ocamlc option from custom patch not working)

EDIT: it looks like the ocaml backend was the issue. The kdoc is known not to work. It might be a good idea to keep the java backend the default for now

**Comment by ehildenb** [comment] 2019-09-17 15:27
Ocaml backend is being deprecate, please switch to LLVM backend. KDoc issue is duplicate of https://github.com/kframework/k/issues/41

**Closed as completed by ehildenb** 2019-09-17 15:27 UTC
