### ISSUE TITLE
Do not warn fur unused symbols by default

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/k#1377] opened 2020-06-25 21:34 UTC
As per this discussion: https://github.com/kframework/wasm-semantics/pull/366#discussion_r445815170

Top-level cells in K might be considered "externally visible", and are expected to be used for configuration composition. As such, they should not have to be labeld `unused` explicitly.

**Comment by denis-bogdanas** [comment] 2020-06-26 17:51
Not just top-level cells but any cells that has used sub-cells. In KEVM we get:
```
[Warning] Compiler: Symbol '<network>' defined but not used. Add the 'unused'
attribute if this is intentional.
```

**Comment by ehildenb** [comment] 2020-06-26 17:57
We had the discussion about sub-cells which aren't used. I agree with @denis-bogdanas that it's useful abstraction to group cells into sub-cells without ever referring directly to that sub-cell in the definition, so I think we should not report the `<network>` cell in KEVM (or the `<curFrame>` cell in KWasm) as unused. Instead the warning should be about a cell like `<foo> 0:Int </foo>` or `<foo> <bar> 0:Int </bar> <baz> 1:Int </baz> </foo>` where _none_ of the children are used.

This more general rule also covers the case of `<generatedTop>` and any other top-level cells that are used.

**Comment by dwightguth** [comment] 2020-06-26 20:54
I can kinda see both sides on this. On the one hand, documenting configurations is extremely valuable and a way to conceptually group parts of the configuration visually to coders is useful in helping them understand the structure and meaning of a semantics. On the other hand, the symbols in question really /are/ unused; they're providing organizational structure to the code, but they could equally be removed without altering the meaning of the semantics in any way. As such, if we simply suppress the warning entirely, we could end up not warning people who genuinely want to be warned. On top of that, having unused levels of nesting in the configuration structure increases the number of pointer dereferences that need to happen in order to perform pattern matching on a configuration, which makes the semantics slower.

So I'd like for us to come up with some compromise between the two extremes of "everyone has to label every cell as unused that they define and don't use, even when they perform important documentation purposes" and "nobody gets warnings when a cell that groups other cells is never used, even when they might want them". But in order to do that, we need to get to the root of the problem. It's obvious from @ehildenb and @denis-bogdanas that there is some friction associated with the concept of annotating these cells as unused. Is the friction just that they don't "feel" unused, and thus there is dissonance associated with using an attribute named "unused" to describe them, which might make someone reading the code think that they don't matter when in fact they describe a conceptual grouping within the configuration that is meaningful to undersanding? is the concern associated with having to explicitly annotate cells every single time to suppress the warning? or what else is the root cause of the friction? what is it that you feel you have to do now that you don't want to be doing, and is there a way we can get rid of that feeling without actually removing the ability for the compiler to detect an entire category of unused symbols?

**Comment by dwightguth** [comment] 2020-06-26 20:56
One idea I had was just to add some simple, short attribute that means the same thing as unused when it appears on a cell, but conveys a different feeling. Something like, `<network section="">`. What are people's thoughts on this as a solution?

**Comment by ehildenb** [comment] 2020-06-26 21:05
Well, when you mentioned that the example `<network unused="">` means the user will have to consider the performance slowdown, that makes me wonder if we can use this to optimize away those cells from the representation.

But actually, I don't think it's really possible, and an example is exactly the `<network>` cell in KEVM. It _is_ unused for the normal LLVM build, but it _is_ used for the web3 build (because we push/pop the entire `<network>` state). So what cells are considered used or not is dependent on the build of the semantics you have, and we can't have a consistent `unused=""` flag for it.

So I still think that a super-cell with used sub-cells should not be considered unused.

Another option would be to do away with the `unused=""` attribute on cells altogether, but just automatically analyze and _remove_ unused cells. In the case of `<foo> <bar> <baz> </foo>`, where `<foo>` is never mentioned but `<bar>` and `<baz>` are, you could promote `<bar>` and `<baz>` to top-level cells. In the case of a leaf cell that isn't used you just remove it from the configuration. This may introduce some weirdness in unparsing (or some "unexpectedness" as a users cells may disappear), but at least it means we don't have to warn the user at all.

Maybe a better approach in general would be to optimize away _all_ unused symbols, instead of warning that they are unused. That would support the case where you declare extra symbols in a common file, which are only used in some of the ways a semantics is built, but allow optimizations in the case that they are unused.

The more I think about it, the more I don't like the `unused` attribute at all. It doesn't lend itself to extending definitions.

**Comment by ehildenb** [comment] 2020-06-26 21:10
Another example is `krypto.md`, or anything in `domains.k`. What if you import a module and never use one of the hooked symbols defined in it which has no rules associated with it?

**Comment by ehildenb** [comment] 2020-06-26 21:15
See https://github.com/kframework/evm-semantics/pull/843#discussion_r446411104 and https://github.com/kframework/evm-semantics/pull/843#discussion_r446411434 for examples of the awkwardness of this attribute.

In one case, it legitimately caught something unused, so that's :+1:. In the other case, it's a hooked function that does not get used until the semantics is extended in the Web3 build.

So, now I'm thinking, that:

-   This warning should only be turned on with a flag `--warn-unused`.
-   The `unused` attribute should go away, since it just adds confusion to the definition and makes definitions less modular.
-   Any optimizations we want to apply to unused symbols should be done by automatically inferring that a symbol is unused, not based on the attributes.

**Comment by dwightguth** [comment] 2020-06-26 21:37
Your point that in some cases the "global" view of whether something is unused or not is not actually global enough is a good one. It seems that the attribute significantly breaks down in such cases. Another case I've found where that happens is while you are in the process of implementing the semantics. Personally, I wonder whether if we adopted another idea I'm in favor of, which is to make each module explicitly or implicitly export the list of symbols that the modules importing it can see as visible, we could resolve this, because then any externally visible symbol would be considered implicitly used. But that's a change for another day. For the time being, I am comfortable with making this warning be disabled by default and enabled via an option. I will keep the existing behavior of the unused attribute, because it is useful in some cases, although clearly not all, and nothing stops it from not being used, but I will modify the warning text so it is less explicit about suggesting that you add the attribute if it's intentional. The idea of having an "inlining" pass that inlines appearances of symbols if they are the sole constructor of their sort and they always appear under another symbol in every occurrence is a good one, and I agree that we ought to compute such inlining information based on the dynamic snapshot of which modules have been imported that happens after all the modules have effectively been flattened into one, but there's more that would also have to go into such an issue, so I think it merits further discussion elsewhere before being acted upon.

**Comment by hjorthjort** [comment] 2020-06-26 22:09
I agree that if the unused cells slow down the semantics, they should be removed, at least when compiling with an `-O2` flag or similar. I also agree that a flag for turning warnings on makes more sense than having it on by default, at least for configurations. (For rules I think it should be turned on by default: using underscores to denote unused variables is a good idiom and I'm happy to see it enforced. If there is complaints about these warnings, then they can be turned _off_ with a flag.) And lastly, if we have any attribute to surpress the warnings, I agree it should be something more along the lines of `section`, because `unused` gives the wrong idea. We could also consider just adopting the same convention for cells as for variables: prefixing the name by an underscore surpresses the warnings.

**Comment by ehildenb** [comment] 2020-06-26 22:37
Well I don't think we're thinking of changing the used-detection for variables, just for symbols.

I think the simplest fix is to just have this disabled by default, and enabled with a flag. That way you can occasionaly sanitize your definition and remove cruft.

**Comment by hjorthjort** [comment] 2020-06-26 22:41
That makes the second a third point moot then. As for the first point, if it's possible to remove these cells at compile time for a speed-up, I think we should.

**Comment by denis-bogdanas** [comment] 2020-06-29 13:57
I tend to agree with Everett. Unused symbol detection is most useful for variables.

**Comment by hjorthjort** [comment] 2020-07-09 12:27
This seems to have been partly addressed in #847, but the conversation there indicates it didn't completely solve the problem. @denis-bogdanas Did you open another PR? I don't see it.

**Comment by denis-bogdanas** [comment] 2020-07-09 12:44
@hjorthjort No I didn't. PR #847 seems unrelated. It's haskell backend update.

**Comment by hjorthjort** [comment] 2020-07-09 12:49
@denis-bogdanas My bad, I was a bit quick -- 847 was in evm-semantics, and the discussion was related specifically to KEVM.

**Comment by denis-bogdanas** [comment] 2020-07-09 16:43
In https://github.com/kframework/evm-semantics/pull/847 I only eliminated the warnings for variables. Warnings for cells were not touched. We are waiting a fix for this issue that will clean them.

**Comment by ehildenb** [comment] 2020-07-09 18:26
This one is being scheduled, will likely be taken care of next week @denis-bogdanas .

**Closed as completed** 2020-07-17 19:37 UTC
Labels: error-message
