### ISSUE TITLE
[Bug] [kompile] - config composition incurs memory overhead during compilation

### ISSUE THREAD

**Issue by yzhang90** [runtimeverification/k#1799] opened 2021-02-09 04:28 UTC
It seems that the configuration composition incurs huge memory overhead during compilation.
My computer has 32G memory.
- compile the [wasm semantics](https://github.com/kframework/wasm-semantics/commit/457185bce5646b05f02faa989229b0e06bec01a1) (`make build-llvm`).  The memory consumption is ~5.8% and it takes ~2mins to finish.
- compile the [elrond semantics](https://github.com/runtimeverification/elrond-semantics/commit/f3c59535950004c08de5625611a9e09ec2c4e32a) (`make build-llvm`). I remove all the rules in `elrond.md` and only keep the configuration composition. The memory consumption is ~17.8% and it takes ~2min 40s to finish.
- compile the full elrond semantics. The memory consuption is ~35% and it takes ~19mins to finish (llc takes 8mins).
- adding more rules incur more memory overhead. Compiling  fix_lottery branch of the elrond semantics doesn't finish in half an hour.

**Comment by ehildenb** [comment] 2021-02-09 18:53
Likely it's an issue with decision tree generation process, because KWasm uses the `<instrs>` cell instead of the `<k>` cell for execution. `<k>` cell is expected to be added by the embedding, so maybe the decision tree generation process is choking on the Elrond semantics adding the `<k>` cell, and for each pair of constructors on top of the `<k>` and `<instrs>` cells, you need to provide a check in the decision tree.

Add this to `kompile`: `--heuristic 'oqbaL'`, and see if it fixes the issues. Post results here.

**Comment by yzhang90** [comment] 2021-02-09 19:55
I added the flag to compile the elrond semantics under `fix_lottery` branch. Here is the result:
with heuristic flag:  java peak memory 26.6%, llc-8 memory ~27.3%,  total time 9m 50s
without flag: java peak memory > 45%, llc-9 memory > 10%, didn't finish in 20mins. killed

**Comment by dwightguth** [comment] 2021-02-09 20:14
I can confirm that with the oqbaL or oqbaR heuristic, decision tree generation finishes in a fairly reasonable amount of time (~30s). oqbaR seems to perform a tiny bit better, but the difference isn't really noticeable. It definitely seems to take a ridiculously long time to run llc on the generated code, but that seems to be because the generated code is extremely large by comparison to otherwise much bigger semantics. The new C semantics is over 3x as many rules, but it generates an actually smaller binary. Examining the size of the decision trees that are generated, we find that the total size of the Elrond decision tree is roughly 10% the size of C's decision tree, but the shared size is actually over 3x bigger, telling us that sharing is roughly 30x worse than normal. This explains why the generated code is so much bigger and thus slower to compile.

I could probably dig deeper and try to find other ways to improve sharing, but honestly, your best bet is still to solve the algorithmic issues that lead to the split between the k cell and the instructions cell when matching. If you can solve that, you should see a much smaller binary, a binary that spends significantly less time matching (although matching is probably not the bottleneck either way), and also one that compiles much more quickly without needing to rely on the `o` heuristic.

I will see if I can find any obvious places where the performance of llc can be improved, though.

**Comment by dwightguth** [comment] 2021-02-09 22:03
I've been able to identify that llc takes roughly 5 minutes to do register allocation, 2 minutes to do instruction selection, 1 minute writing the assembly to a file, and trace amounts elsewhere. I also was able to identify that something like 55% of execution time of llc was spent in a single function in LLVM, llvm::MachineRegisterInfo::hasOneNonDBGUse. It seems that this function is supposed to compute whether a particular machine register has exactly one use in a function. It seems to do this in linear time in the size of the function. Since this function is potentially called on each instruction in the function, that makes the register allocation pass quadratic. Most likely this is the source of the problem, since we have generated some quite large functions in the form of a large decision tree. I am going to try to send a message to the llvm mailing list asking for advice about what can be done here (aside from obviously reducing the size of the function), but any results we get are likely to not affect us in practice for a period of several months while we wait for the next LLVM release, even if I manage to come up with a patch to improve this. As such, I strongly recommend that you attempt to reduce the size of the decision tree using the mechanisms I previously mentioned.

**Comment by ehildenb** [comment] 2021-02-09 23:01
@dwightguth is there not a way to change the way the decision trees are generated to make them smaller?

Asking devs to "reduce the size of the decision tree" when we only have the faintest shadows of ideas about how the decision trees are generated is a bit counter-prooductive. If that's the solution, then we need documentation about how the decision trees are generated, so we can know which cases are pathological. But I think the proper way to handle this is in the generation of the decision trees themselves. We should be able to handle semantics written in this way, esp since this is an LLVM-backend specific thing, not something that plagues K in general.

**Comment by yzhang90** [comment] 2021-02-10 22:11
@dwightguth @ehildenb I tried to add `[priorities(20)]` to all the rules that do not mention `instrs` cell in the elrond semantics:
1. with heuristic flag:      java mem: 23.7%     opt-8 mem: 9.3%     time: 7m 35s
2. without heuristic flag: java mem:30.9%      llc-8 mem: 12%        time: 9m 40s

**Comment by ehildenb** [comment] 2021-02-10 22:20
@yzhang90 did you say `priorities(20)` or `priority(20)`? the first will do nothing, the second is what you want.

Also, I would think you would want `priority(60)` innstead (make those rules only happen after rules with `<instrs>` cell fires)

**Comment by yzhang90** [comment] 2021-02-10 22:29
@ehildenb  sorry, typo. I did write `[priority(20)]` in the elrond semantics.
Regarding the priority number...I'm not sure, because they are two separate set of rules (they do not overlap with each other). The typical flow is k cell is doing some job and then put `#wait` on top of the k cell and initialize the `instrs` cell. Then wasm semantics take over. After wasm finish its job, the following rule will be fired:
```
  syntax Step ::= "#wait"
 // -----------------------
    rule <k> #wait => . ... </k>
         <commands> . </commands>
         <instrs> . </instrs>
```
so I do not know which set of rules should have higher priority :)

**Comment by yzhang90** [comment] 2021-02-11 17:29
Interesting, if I update priority from 20 to 60, then
with heuristic flag: java mem: 20.2% opt-8 mem: <5% time: 5m 11s
without heuristic flag: java mem:21.4%  llc-8 mem: <5% time: 5m 35s

**Comment by dwightguth** [comment] 2021-03-01 22:03
The program that took 10 minutes to llc with llvm 11 takes only 2.5 minutes to llc with llvm 12 rc 2. So it looks like someone actually already fixed this issue and we're just waiting for the next release of llvm to ship, which is probably going to be relatively soon. In the meantime, if it recurs at some point, we can just have developers build with llvm 12.

As such, I am going to close this issue as having been completely resolved.

**Closed as completed by dwightguth** 2021-03-01 22:03 UTC
Labels: bug
