### ISSUE TITLE
[Error] Internal: Uncaught exception thrown of type NoSuchElementException.

### ISSUE THREAD

**Issue by gleguern** [runtimeverification/k#1098] opened 2020-02-12 18:48 UTC
Hi,

I got the error in subject and folow kompile directives to file a bug report.

I use "RV-K version 1.0-SNAPSHOT Git revision: f84831e" (result from kompile --version).

I'm specializing Map for my purpose in a data-type module (attached file data-type.k -- to which I added the .txt suffix in order to be able to upload it here). I wrote a minimal test file (attached file test-record.k) in a repository named 'tests' existing at the same level as data-type.k.

[test-record.k.txt](https://github.com/kframework/k/files/4194324/test-record.k.txt)
[data-types.k.txt](https://github.com/kframework/k/files/4194303/data-types.k.txt)

When running 'kompile --debug test-record.k' I get the following stack trace:
SortGeneratedTopCell{}
inj{SortRecordDescr{}, SortKItem{}}
java.util.NoSuchElementException: key not found: inj{SortRecordDescr{}, SortKItem{}}
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:97)
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:95)
	at org.kframework.backend.llvm.matching.Fringe.injections(Matrix.scala:235)
	at org.kframework.backend.llvm.matching.Column.$anonfun$signatureForKey$2(Matrix.scala:112)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.kframework.backend.llvm.matching.Column.signatureForKey(Matrix.scala:112)
	at org.kframework.backend.llvm.matching.BHeuristic$.computeScoreForKey(Heuristics.scala:135)
	at org.kframework.backend.llvm.matching.AbstractColumn.computeScoreForKey(Matrix.scala:33)
	at org.kframework.backend.llvm.matching.AbstractColumn.computeScoreForKey$(Matrix.scala:17)
	at org.kframework.backend.llvm.matching.Column.computeScoreForKey(Matrix.scala:45)
	at org.kframework.backend.llvm.matching.Column.zeroOrHeuristic$2(Matrix.scala:79)
	at org.kframework.backend.llvm.matching.Column.$anonfun$computeScoreForKey$1(Matrix.scala:82)
	at org.kframework.backend.llvm.matching.Column.$anonfun$computeScoreForKey$1$adapted(Matrix.scala:82)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at org.kframework.backend.llvm.matching.Column.computeScoreForKey(Matrix.scala:82)
	at org.kframework.backend.llvm.matching.Column.computeScore(Matrix.scala:71)
	at org.kframework.backend.llvm.matching.Column.score$lzycompute(Matrix.scala:57)
	at org.kframework.backend.llvm.matching.Column.score(Matrix.scala:57)
	at org.kframework.backend.llvm.matching.Column.score(Matrix.scala:67)
	at org.kframework.backend.llvm.matching.MatrixColumn.score$lzycompute(Matrix.scala:42)
	at org.kframework.backend.llvm.matching.MatrixColumn.score(Matrix.scala:42)
	at org.kframework.backend.llvm.matching.Heuristic$.getBest(Heuristics.scala:27)
	at org.kframework.backend.llvm.matching.Matrix.bestColIx$lzycompute(Matrix.scala:447)
	at org.kframework.backend.llvm.matching.Matrix.bestColIx(Matrix.scala:442)
	at org.kframework.backend.llvm.matching.Matrix.compileInternal(Matrix.scala:622)
	at org.kframework.backend.llvm.matching.Matrix.compile(Matrix.scala:603)
	at org.kframework.backend.llvm.matching.Matching$.writeDecisionTreeToFile(Matching.scala:26)
	at org.kframework.backend.llvm.matching.Matching.writeDecisionTreeToFile(Matching.scala)
	at org.kframework.backend.llvm.LLVMBackend.accept(LLVMBackend.java:48)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:74)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:108)
	at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type NoSuchElementException (key
not found: inj{SortRecordDescr{}, SortKItem{}})

It may be due to bad usage of K, but as kompile asks to file a bug report, I do. Is it a problem on my side, or kompile's side ?

Thanks

**Comment by dwightguth** [comment] 2020-02-12 19:44
This is definitely a bug in the tool. The following rule:

```
  rule record2descr( ( F:Id |-> V ):Record ) => ( ( F = V ):RecordFieldDescr ):RecordDescr [structural]
```

is being parsed incorrectly. The rhs of the rewrite is being parsed as sort RecordFieldDescr instead of RecordDescr, so the code crashes unexpectedly because the rhs of the rewrite of a function rule is not a subsort of the lhs. It's supposed to be interpreting the rhs as a list of length 1, but this is not happening for some reason. You can write the list terminator manually, however, like so:

```
  rule record2descr( F:Id |-> V ) => F = V ; .RecordDescr [structural]
```

This seems to happen only when the rule is a function rule and the list element appears at the top of the rhs of the rewrite. I will investigate the root cause, but for now, this workaround will unblock you.

**Comment by dwightguth** [comment] 2020-02-13 21:15
Incidentally, this is unrelated to your bug, which I have a patch for that I am testing now, but I notice you wrote:

```
  syntax RecordDescr ::= "record2descr(" Record ")" [function]
```

You probably meant:

```
  syntax RecordDescr ::= "record2descr" "(" Record ")" [function]
```

or simply:

```
  syntax RecordDescr ::= record2descr(Record) [function]
```

What you wrote tells the scanner to create a single token `record2descr(` instead of two tokens, `record2descr` and `(`, which means that you would get a parsing error if you wrote `record2descr ( F:Id |-> V )` (note the space between the name of the function and the open parentheses).

**Comment by dwightguth** [comment] 2020-02-14 20:07
PR #1104 appears to fix this issue and is passing our tests. It won't get merged until Monday because I am waiting on a review from someone who is busy with other things today, but you can build the `emptylists` branch of K from source if you want to unblock yourself.

**Closed as completed** 2020-02-19 22:51 UTC

**Comment by gleguern** [comment] 2020-02-21 14:26
The work around worked fine for me. Thanks
